# Generated by Django 5.2.12 on 2026-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('studio', 'Studio'), ('apartment', 'Appartement'), ('room', 'Chambre'), ('villa', 'Villa'), ('land', 'Terrain')], max_length=20)),
                ('neighborhood', models.CharField(max_length=120)),
                ('city', models.CharField(default='Lomé', max_length=100)),
                ('country', models.CharField(default='Togo', max_length=100)),
                ('gps_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('gps_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
